### ISSUE TITLE
[BUG] | Unable to put a character of the same Voidwalker religion on Council

### ISSUE THREAD

**Issue by TonyGoldelf** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#127] opened 2019-02-07 09:56 UTC
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.2

**What expansions do you have installed?**
Holy Fury, Horse Lords, Monks and Mystics, The Reaper's Due, Horse Lords, Way of Life, Charlemagne, Sons of Abraham, The Old Gods, The Republic, Sunset Invasion, Legacy of Rome, Sword of Islam

**Please explain your issue in as much detail as possible:**
My friend and I got a problem in multiplayer: he was a Quel'Thalas high elf (Kael'Thas) who decided to change his religion to Voidwalker. He announced it openly and converted the vassals, also made usage of Dark Magic allowed by laws.

The problem is that he than became unable to put his Voidwalker vassals on the Council. They just disappeared from the list whom to put on. He was Voidwalker, too.
**Steps to reproduce the issue:**
1. Choose Quel'Thalas
2. Change your character religion to Voidwalker
3. Convert a Council member religion to Voidwalker
= He deletes himself from the list of people available to be put on Council

**Upload an attachment below: .zip of your save, or screenshots:**
No saves or screenshots left =(

**Comment by zumbak04** [comment] 2019-02-07 22:32
What сouncil position are you talking about?
https://ck2.paradoxwikis.com/Council#Positions
If it's the Court Chaplain, only either the shadow priests (class) or characters with the learning education, but without any class can be appointed if you follow the Void. Plus, it must be a non-ruler or a theocratic.

**Comment by TonyGoldelf** [comment] 2019-02-08 08:28
I'm talking about all council positions: chancellor, martial, etc...

My friend just couldn't assign any of the Voidwalker vassals. They disappeared from the list of people available to be put on Council right after accepting new religion.

**Comment by MemeWizard** [comment] 2019-02-08 16:37
>I'm talking about all Council positions: chancellor, martial, etc...

Can't reproduce. Need more info.

<details>
<summary>Click to expand</summary>

![ck2_2](https://user-images.githubusercontent.com/46576860/52490032-e1087600-2bd4-11e9-8612-a12bf757bb64.png)
![ck2_1](https://user-images.githubusercontent.com/46576860/52490033-e1087600-2bd4-11e9-8943-17d5679ddce8.png)

</details>

**[RU]**
>Мне так же кажется, что пару прохождений назад подобная проблема была у него после принятия Скверны.

Могу разве что предположить, что вассалы автоматически увольнялись игрой, а обратно игроком не могли назначаться, потому что были недавно уволены.

**Comment by zumbak04** [comment] 2019-02-08 22:41
> I'm talking about all Council positions: chancellor, martial, etc...
> 
> My friend just couldn't assign any of the Voidwalker vassals. They disappeared from the list of people available to be put on Council right after accepting new religion.

Were these vassals members of the Council before? If they were, and then after the change of religion were fired, then it's already fixed.

**Comment by TonyGoldelf** [comment] 2019-02-08 22:54
They were members of the Council before and after accepting new Voidwalker religion they leave positions and are never shown on the list.
You mean we need to wait till 1.3+ or what?

**Comment by zumbak04** [comment] 2019-02-08 23:22
Till 1.3, it was fixed a few days before.

**Comment by TonyGoldelf** [comment] 2019-02-08 23:25
Oh thank you true gods of Azeroth!
So when may we get the 1.3 version? ^ ^

**Comment by zumbak04** [comment] 2019-02-08 23:28
It's not a report thing, you can just ping me on the Discord server, but fine...
About a week.
I'm closing the issue. Thanks for reporting and supporting.

**Closed by zumbak04** 2019-02-08 23:28 UTC
Labels: :beetle: bug :beetle:
