### ISSUE TITLE
No character can join society after game reloading

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#908] opened 2019-11-05 04:45 UTC
**Mod Version**
136c94f4

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**

Sometimes "No character" with "Rebels" name joins society.

This things probably can be related:

> [character.cpp:27448]: Character 'Fitch of ---(2100888)' has invalid religion
> [character.cpp:27448]: Character 'Darrel of ---(2100889)' has invalid religion

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/68179258-417be680-ffa0-11e9-8b44-5153498d83c1.png)

</details>

**Steps to reproduce the issue:**
Save and reload the game

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/68179227-18f3ec80-ffa0-11e9-876a-aa7936a0d2a1.png)

</details>

**Comment by zumbak04** [comment] 2019-12-01 17:25
@MemeWizard can't reproduce it. I played some time, saved game and loaded. Don't see this error in log. Do you have save where this error is always visible?

**Comment by MemeWizard** [comment] 2019-12-02 02:57
> Don't see this error in log.

<details>
<summary>Weird</summary>

![image](https://user-images.githubusercontent.com/46576860/69925463-5ffed000-14c1-11ea-962e-1b332e483f66.png)

</details>

> Do you have save where this error is always visible?

What error? "Rebels in society" or "Character has invalid religion"?

**Comment by zumbak04** [comment] 2019-12-03 14:57
> Idk how to reproduce first, but I have second in my error.log after loading any save.

@MemeWizard , do you see this error here?
[Frostmane583_01_22.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3917222/Frostmane583_01_22.zip)

And please send me your save where you have the error.

**Comment by MemeWizard** [comment] 2019-12-03 15:13
> do you see this error here?

Yep

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/70063094-47450600-15f8-11ea-8037-2931444dbd41.png)

</details>

> And please send me your save where you have the error.

Well, if you wish so

[Frostmane583_01_23.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3917310/Frostmane583_01_23.zip)

**Comment by zumbak04** [comment] 2019-12-03 15:34
Got it. I shold switch to 3.3.0 to see this error.

**Comment by zumbak04** [comment] 2019-12-25 18:14
Should be fixed.

**Closed by zumbak04** 2019-12-25 18:14 UTC
Labels: :beetle: bug :beetle:, :exclamation: priority high, :x: info needed :page_facing_up:
