### ISSUE TITLE
Cho'Gall moving to Kalimdor

### ISSUE THREAD

**Issue by Ectheldir** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#677] opened 2019-08-24 16:55 UTC
**DO NOT REMOVE PRE-EXISTING LINES**
----------------------------------------------------------------------------------------------------------
**Describe your suggestion in full detail below:**

There are a bunch of weird things happening, when Cho'Gall moves to Kalimdor, which might be improved upon.

1. You lose some members of your court, but not all. It seems a bit random, which follow and which don't. But, those that follow, hate you, as you are now openly Shath'yar, but they are still Fel.

2. You lose you wife. At least I did. She stayed in Azeroth and now hates me. Well, back to Ogre-wife spawning...

3. While you loose your original holdings, you will keep any raised troops and also you generals. They will just stop doing whatever they did before. They are also really useless in the east. 
I was wondering why I couldn't declare any war, till I found them standing there.

Just some stuff I noticed. No, idea, if these are fixable or natural limitations.

**Comment by Ectheldir** [comment] 2019-08-24 17:04
Also noticed this: In the laws parts it claims that you are part of the Horde and the Qirajid-Empire, while you are not (as far as I can tell)
![Screenshot (61)](https://user-images.githubusercontent.com/51327482/63640552-effed380-c6a1-11e9-8bac-793459caed19.png)

**Comment by zumbak04** [comment] 2019-08-24 17:06
> Also noticed this: In the laws parts it claims that you are part of the Horde and the Qirajid-Empire, while you are not (as far as I can tell)

You're part of de-jure Ahn'qiraj.

**Comment by zumbak04** [comment] 2019-08-24 17:13
> 3. While you loose your original holdings, you will keep any raised troops and also you generals. They will just stop doing whatever they did before. They are also really useless in the east.
>    I was wondering why I couldn't declare any war, till I found them standing there.

Didn't get this part. Agains who you was trying to declare war?

**Comment by Ectheldir** [comment] 2019-08-24 17:16
When I was trying to declare war, after I moved to Kalimdor, I was confused, because I had the troops raised in Azeroth. I assumed, as there was no land I held, I also had no troops left there.

**Comment by zumbak04** [comment] 2019-08-24 17:24
> 2. You lose you wife. At least I did. She stayed in Azeroth and now hates me. Well, back to Ogre-wife spawning...

Most likely she left because you started openly worship the Old Gods.

**Comment by zumbak04** [comment] 2019-08-24 17:44
> When I was trying to declare war, after I moved to Kalimdor, I was confused, because I had the troops raised in Azeroth. I assumed, as there was no land I held, I also had no troops left there.

Got it. Your troops were raised when you sailed to Kalimdor. Only Paradox can fix it. You can do the same thing in vanilla: raise troops in province and give province to your vassal.

**Comment by zumbak04** [comment] 2019-08-24 17:46
> 1. You lose some members of your court, but not all. It seems a bit random, which follow and which don't. But, those that follow, hate you, as you are now openly Shath'yar, but they are still Fel.

Tried it a few times. Lost only wife. Need steps to reproduce or saved game before you sailed.

**Comment by Ectheldir** [comment] 2019-08-24 20:17
> Tried it a few times. Lost only wife. Need steps to reproduce or saved game before you sailed.

Sorry, I was stupid. I looked at the save before and found out that my wife was my chancellor. That's why my chancellor was suddenly gone.
Sorry.

Btw, while I lost my wife I kept my children, who are also Fel. But, this might be intentional.

**Comment by zumbak04** [comment] 2019-08-27 20:00
> Btw, while I lost my wife I kept my children, who are also Fel. But, this might be intentional.

Yep, they're going to inherit everything anyway.
Ok, looks like I answered all the questions so I'm closing the issue. Reopen it if there's something left.

**Closed by zumbak04** 2019-08-27 20:00 UTC
Labels: :page_facing_up: info needed :question:, :question: suggestion :question:
