### ISSUE TITLE
Land of the Dead not removed by Culling

### ISSUE THREAD

**Issue by johncawks** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#21] opened 2019-01-18 06:02 UTC
*Which version of the mod does this apply to?

Current (1.2)

*How important is this bug/suggestion (Low/Medium/High/Critical)?

Medium.

*Explain the bug or suggestion below:

When using the Culling option to cleanse a province of undead, the Land of the Dead modifier does not go away, despite depopulating, destroying buildings, and killing garrisons/levies. I Culled a province over 3 times and it never went away. 

*Feel free to attach a **.zip** or a **screenshot** of the bug to better help us understand the issue.

**Comment by zumbak04** [comment] 2019-01-18 12:55
Tested it a few times. Don't see this issue in the game. Your save needed.

**Comment by johncawks** [comment] 2019-01-19 03:20
Context: This is a multiplayer game that started at the Opening of the Dark Portal bookmark. Despite never being conquered my provinces turned Scourge/Death God and gained the Land of the Dead modifier*. I culled them three or four times. This is backed up by the fact that the culture and religion of the provinces has already changed (some are even still depopulated). 

*I assumed this was due to the plague and the fact that players turn independent after the Scourge wins in Lordaeron.

[Blackwood622_09_15.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/2775100/Blackwood622_09_15.zip)

**Comment by zumbak04** [comment] 2019-01-19 13:37
> Despite never being conquered my provinces turned Scourge/Death God and gained the Land of the Dead modifier.

It's because of the Plague.

I couldn't reproduce your bug. I need your checksum and DLC's list.

I have one idea. Try to do the same in the singleplayer game. If everything works fine, no need in your checksum and DLC's list.

**Comment by zumbak04** [comment] 2019-02-13 14:31
Made a temporary fix. I'm not sure that this actually fixes the issue, because I still need more info.

**Comment by zumbak04** [comment] 2019-07-17 15:24
Closing the issue. If it still happens, reopen it.

**Closed by zumbak04** 2019-07-17 15:24 UTC
Labels: :beetle: bug :beetle:, :grey_exclamation: priority low
