### ISSUE TITLE
[LOCALIZATION] | Libram Loc

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#505] opened 2019-07-15 15:40 UTC
**Mod Version**
b6c05597

**Please explain your issue in as much detail as possible:**
Libram Loc is wrong
Alonsus gave Libram to Thoras, not Gavinrad

**Upload screenshots of the problem localization:**

<details>

![image](https://user-images.githubusercontent.com/46576860/61228816-ab415d80-a72f-11e9-95cc-7fc96fda7c1c.png)

</details>

**Comment by DukeJeans** [comment] 2019-07-15 16:01
Fixed in ec5f033e

**Comment by DukeJeans** [comment] 2019-07-15 16:16
Duke did an oopsie

**Comment by arithon** [comment] 2019-07-15 21:28
You sure about that? https://wow.gamepedia.com/Libram_(relic)
Here it says, Faol gave it to Gavinrad...

**Comment by DukeJeans** [comment] 2019-07-15 21:48
> You sure about that? https://wow.gamepedia.com/Libram_(relic)
> Here it says, Faol gave it to Gavinrad...

The issue is that the mod occurs during the same time these Librams were passed out to said Paladins, so it won't be Alonsus and Gavinrad each time. In the case that the leader of the Church is not Alonsus Foal or the Paladin is not (e.g. Gavinrad) the correct paladin, then the localisation needs to adapt.

**Comment by DukeJeans** [comment] 2019-07-16 05:12
Fixed in e1c8c82e.

![image](https://user-images.githubusercontent.com/32686241/61267642-aba91b00-a766-11e9-94a0-11c213e7fe91.png)

![image](https://user-images.githubusercontent.com/32686241/61267657-b794dd00-a766-11e9-8bcc-fa1d3a18a254.png)

**Closed by DukeJeans** 2019-07-16 05:12 UTC
Labels: :beetle: bug - localization :scroll:, :grey_exclamation: priority low
