### ISSUE TITLE
[BUG] | Cenarius summoning the Burning Legion to destroy life...wait a minute.

### ISSUE THREAD

**Issue by Varus211** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#109] opened 2019-02-02 15:44 UTC
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
### **One line summary of your issue:**
Cenarius joining Shadow Council, summoning Archimonde without a fight.
**Mod Version**
Current Release
**What expansions do you have installed?**
All
**Please explain your issue in as much detail as possible:**
So I'm playing Garithos and forging my kingdom from the Forsaken, when I get the usual invasion event..but then I notice it was Cenarius who summoned them, so they didn't even fight for the World tree.

**Steps to reproduce the issue:**
Have Cenarius join the shadow council,
Not sure if the world tree counts as a source of power but get that/3 magical artifacts.

**Upload an attachment below: .zip of your save, or screenshots:**
![image](https://user-images.githubusercontent.com/47144221/52166146-5e029e00-2744-11e9-8268-17167c0d7137.png)

**Comment by zumbak04** [comment] 2019-02-03 15:08
Ye, Nordrassil holding is a source of power, so Cenarius used its magic to summon the Legion. The war against holder of Nordrassil is the only scripted war Legion have. After that, the Legion is free to do what it sees fit.

**Comment by zumbak04** [comment] 2019-02-05 19:21
I'll close this issue since it's not a bug.

**Closed by zumbak04** 2019-02-05 19:21 UTC
Labels: :beetle: bug :beetle:, :grey_exclamation: priority low

**Comment by ManuSwaG** [comment] 2019-02-06 06:19
Wait, why is this not a bug?
