### ISSUE TITLE
[SUGGESTION] | Kaldorei Religion Rename

### ISSUE THREAD

**Issue by Hamstarox** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#1022] opened 2019-12-19 16:40 UTC
**Describe your suggestion in full detail below:**
Renaming the Night Elf faith to "Elune" instead of "Kaldorei". Currently the culture and the religion are named the same which leads to confusion when attempting to differentiate (The game will say you are a Kaldorei Kaldorei for example

**Comment by MemeWizard** [comment] 2019-12-19 23:21
Closed, since it's duplicate of #958

**Closed by MemeWizard** 2019-12-19 23:21 UTC
Labels: :exclamation: priority high, :question: suggestion :question:
