### ISSUE TITLE
[BUG/SUGGESTION] Reign of Chaos Bookmark

### ISSUE THREAD

**Issue by Mizarix** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#39] opened 2019-01-21 15:43 UTC
So upon playing Reigns of Chaos, there is one character interesting which I selected to play.

What I noticed is after a few months of playing, you are removed from the cult of the damned because you do not uphold the ideals of the society, meaning you are not part of the scourge attack/proper story mode.

I also want to add theres very little story to this nor is there any decisions you can really do which makes this bookmark over very quickly and uninteresting.

**Comment by zumbak04** [comment] 2019-01-24 13:32
> What I noticed is after a few months of playing, you are removed from the cult of the damned because you do not uphold the ideals of the society, meaning you are not part of the scourge attack/proper story mode.

Most likely it happened because the Death God religion stopped being your true religion. If it wasn't the cause, then report it on this issue.

> I also want to add theres very little story to this nor is there any decisions you can really do which makes this bookmark over very quickly and uninteresting.

We're working on a lot of events after/during this bookmark.

**Comment by Mizarix** [comment] 2019-01-24 16:13
Nope, his religion was still secretly practicing the religion.

**Comment by zumbak04** [comment] 2019-07-17 15:41
Closing the issue since there's no info about the bug and I couldn't reproduce it. If it still happens, reopen the issue.

**Closed by zumbak04** 2019-07-17 15:41 UTC
Labels: :beetle: bug :beetle:, :grey_exclamation: priority low
