### ISSUE TITLE
Lick King champion don't lose friends/lovers

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#909] opened 2019-11-05 20:16 UTC
**Mod Version**
40a7e58d

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Lick King champion don't lose friends/lovers

**Steps to reproduce the issue:**
Load save
Don't play as Lick King champion

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/68242347-68c6c800-0021-11ea-925b-5db79832e0b3.png)
![image](https://user-images.githubusercontent.com/46576860/68242335-619fba00-0021-11ea-95a2-bc2c5143327c.png)

</details>

[Kul_Tiras603_03_27.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/3811019/Kul_Tiras603_03_27.zip)

**Comment by zumbak04** [comment] 2020-07-07 11:58
Tried to reproduce the bug on 06ff0d24049f3862c4bfaa8f0cd3333f31acf5ee.
Looks like it's fixed in 7e34fd171b5824825d462eb097d854c015cfd5e4.

**Closed by zumbak04** 2020-07-07 11:58 UTC
Labels: :beetle: bug :beetle:, :grey_exclamation: priority medium
