### ISSUE TITLE
[BUG] | Game ended when the horde won the first war and i was playing Kilrog Deadeye

### ISSUE THREAD

**Issue by sicknot1** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#577] opened 2019-07-30 03:04 UTC
**DO NOT REMOVE PRE-EXISTING LINES**
------------------------------------------------------------------------------------------------------------
**Mod Version**
1.5
**What expansions do you have installed?**
All
**Please explain your issue in as much detail as possible:**
Game ends as soon horde wins when you are playing as character killrog of house Deadeye
**Steps to reproduce the issue:**
Play as him and see if it repeats
**Upload an attachment below: .zip of your save, or screenshots:**
forgot to take pic

**Comment by MemeWizard** [comment] 2019-07-30 03:16
>Game ends as soon horde wins when you are playing as character killrog of house Deadeye

Can't confirm

<details>

![image](https://user-images.githubusercontent.com/46576860/62097986-4b9b9400-b291-11e9-96f4-2aa70b5a3020.png)

</details>

Did you have an heir? If no, Kilrogg probably just died of old age.

**Comment by zumbak04** [comment] 2019-07-30 16:06
> Can't confirm

Me neither.

**Comment by zumbak04** [comment] 2019-08-08 14:30
Closing it due to the lack of info. If you find steps to reproduce reopen this issue or open a new one.

**Closed by zumbak04** 2019-08-08 14:30 UTC
Labels: :beetle: bug :beetle:, :grey_exclamation: priority low
